#!/usr/bin/env python3
"""Run evaluation on the reserved test split using a saved checkpoint."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Mapping, Sequence, Tuple

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from models.LogisticRegression import LogisticRegression
from scripts.data_utils import build_dataset, load_feature_index, read_scan_csv
from scripts.eval_utils import evaluate_split


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Test trained model on the held-out frames.")
    parser.add_argument(
        "--csv",
        "-c",
        type=Path,
        required=True,
        help="CSV file containing the LiDAR scans.",
    )
    parser.add_argument(
        "--feature-index",
        "-j",
        type=Path,
        required=True,
        help="Feature index JSON produced by the generator.",
    )
    parser.add_argument(
        "--checkpoint",
        "-k",
        type=Path,
        default=Path("checkpoints/linear_wall_checkpoint.json"),
        help="Checkpoint JSON generated by `scripts/train.py`.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.checkpoint.exists():
        raise SystemExit(f"{args.checkpoint} does not exist; run train first.")
    with args.checkpoint.open("r", encoding="utf-8") as handle:
        checkpoints = json.load(handle)
    test_frames = checkpoints.get("test_frames") or []
    if not test_frames:
        raise SystemExit("No test frames recorded in checkpoint.")
    threshold = checkpoints.get("threshold", 0.25)
    feature_map, feature_payload = load_feature_index(args.feature_index)
    vector_length = int(feature_payload.get("vector_length", 360))
    frames, frame_vectors, entries = read_scan_csv(args.csv, feature_map)
    test_features, test_labels, test_meta = build_dataset(
        entries, frame_vectors, vector_length, test_frames
    )
    if not test_features:
        raise SystemExit("No samples found for the test split.")
    frame_results = checkpoints.get("frames", {})
    linear_map: Dict[Tuple[int, int], Mapping[str, float]] = {}
    for frame_key, frame_data in frame_results.items():
        frame_index = int(frame_key)
        for point in frame_data.get("point_info", []):
            linear_map[(frame_index, int(point["scan_index"]))] = point
    logistic_state = checkpoints["logistic"]
    logistic = LogisticRegression.from_dict(logistic_state)
    metrics = evaluate_split(
        "test",
        test_features,
        test_labels,
        test_meta,
        logistic,
        linear_map,
        threshold,
    )
    if metrics["logistic_accuracy"] is not None:
        print(f"Test logistic accuracy: {metrics['logistic_accuracy']:.3f}")
    if metrics["ensemble_accuracy"] is not None:
        print(f"Test ensemble accuracy: {metrics['ensemble_accuracy']:.3f}")


if __name__ == "__main__":
    main()
